# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lpgonghan.github.io/
date_format: "ordinal"
title: 寒咯
subtitle: "Talk is cheap, show me the code."
description: "寒的个人博客"
keywords: 寒咯, 寒, Xuehan Gong, hanlo
favicon: /icon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Xuehan Gong
organization: Ladybees
organization_url: http://ladybees.com/
github_username: lpgonghan
location: Shanghai, China
email: lpgonghan@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: lpgonghan/lpgonghan.github.io

# TODO: 分析，评论，脑图插件。
# # ---------------- #
# #      Comments    #
# # ---------------- #
# # support provider: disqus, netease_gentie
# comments_provider: netease_gentie
# # !!!重要!!! 请修改下面这些信息为你自己申请的
# # !!!Important!!! Please modify infos below to yours
# disqus_username: mzlogin
# netease_gentie_key: 560ed243b708465d82d5a0a5f3b83da1
# # 在使用网易云跟帖时可点击显示 Disqus
# lazy_load_disqus : true

# # ---------------- #
# #    Analytics     #
# # ---------------- #
# google:
#     analytics_id: UA-80669434-1
